'use strict';
const ASSETS={bg:'assets/mobile/village.webp',fg:'assets/mobile/village_front.webp',player:'assets/mobile/player.webp',maelith:'assets/mobile/maelith.webp',eira:'assets/mobile/eira.webp',brannoc:'assets/mobile/brannoc.webp',siofra:'assets/mobile/siofra.webp'};
const WORLD={ox:124,oy:1400,w:1280,h:900,spawn:[764,2058]};
const NPC=[
{id:'maelith',name:'Maelíth',role:'Storyteller',x:577,y:1566,line:'The old roads remember every traveler who has crossed Bré Thiar.'},
{id:'eira',name:'Eira',role:'Path Guide',x:895,y:1548,line:'Every Path begins with a choice. Choose the one you can live with.'},
{id:'brannoc',name:'Brannoc',role:'Town Warden',x:573,y:1758,line:'Keep your blade close beyond the village fences. Rowanwood has teeth.'},
{id:'siofra',name:'Siofra',role:'Shrine Keeper',x:854,y:1856,line:'Listen to the stones before you speak. They remember more than we do.'}
];
const COLLISION='/////////////////////5///////wf//////wf//////wf+////DwD+////BwD+////B4D/////A8D/////A/D/////B/j//2PwAcD//wHgAQD+/wHgAAD+/wPgAAD+/wdg4A/+/x8g8P///38A8P////8OiP////8PBP////8PAv7///8PAP7///8HAP7///8DAP7///8DAP////8DiP////8D+P////8H+P////8H/P////8P/v////8P/v////8P/v////8f/P////8f/P////8P+P////8P8P////8P8P//AQAAAAD8AQAAAAD8AQAAAAD8AQAAAAD8AQDwHwD8AQDwHwD8AQDwHwD8wT/wHwD8wT8AAAD8wT8AAAD8wT8AAAD8AQAAwAP8AQAAwAP8AfwAwAP8AfwAAAD8AfwAgH/8AQAAgH/8eQAAgH/8eQAAgH/8eQAAAAD8AQAAAAD8AQAAAAD88QMAAAD88QMAAAD88QMAAAD8AfAP/gH8AfAP/gH8AfAP/gH8AfAP/gH8AQAA/gH8AQAAAOD/AQAAAOD/AQAAAOD/////////';
const bits=Uint8Array.from(atob(COLLISION),c=>c.charCodeAt(0)), $=id=>document.getElementById(id), canvas=$('game'),ctx=canvas.getContext('2d',{alpha:false});
let W=innerWidth,H=innerHeight,DPR=1,last=0,running=false,walk=0,frame=0,toastUntil=0; const held=new Set(), img={};
let player={x:WORLD.spawn[0],y:WORLD.spawn[1],f:'up'};
function resize(){W=innerWidth;H=innerHeight;DPR=Math.min(3,devicePixelRatio||1);canvas.width=Math.max(1,Math.floor(W*DPR));canvas.height=Math.max(1,Math.floor(H*DPR));ctx.setTransform(DPR,0,0,DPR,0,0)} addEventListener('resize',resize,{passive:true});resize();
function loadImage(src){return new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(new Error('Could not load '+src));i.src=src})}
(async()=>{try{const entries=Object.entries(ASSETS);let n=0;for(const [k,src] of entries){img[k]=await loadImage(src);n++;$('status').textContent=`Loading production art… ${n}/${entries.length}`}$('status').textContent='Production art ready.';$('enter').disabled=false}catch(e){$('status').textContent='Asset load failed: '+e.message;console.error(e)}})();
function blocked(tx,ty){if(tx<0||ty<0||tx>=48||ty>=72)return true;const i=ty*48+tx;return !!(bits[i>>3]&(1<<(i&7)))}
function valid(x,y){if(x<WORLD.ox+12||x>WORLD.ox+WORLD.w-12||y<WORLD.oy+12||y>WORLD.oy+WORLD.h-8)return false;const pts=[[x-8,y-4],[x+8,y-4],[x-8,y+3],[x+8,y+3]];return pts.every(([px,py])=>!blocked(px/32|0,py/32|0))}
function nearestNPC(max=80){let best=null,dist=max;for(const n of NPC){const d=Math.hypot(player.x-n.x,player.y-n.y);if(d<dist){best=n;dist=d}}return best}
function toast(t){$('toast').textContent=t;$('toast').classList.remove('hidden');toastUntil=performance.now()+1900}
function label(text,x,y,color='#fff'){ctx.save();ctx.font='600 11px system-ui';ctx.textAlign='center';ctx.lineWidth=3;ctx.strokeStyle='#000c';ctx.strokeText(text,x,y);ctx.fillStyle=color;ctx.fillText(text,x,y);ctx.restore()}
function camera(zoom){const vw=W/zoom,vh=H/zoom;return {x:Math.max(WORLD.ox,Math.min(WORLD.ox+WORLD.w-vw,player.x-vw/2)),y:Math.max(WORLD.oy,Math.min(WORLD.oy+WORLD.h-vh,player.y-vh/2)),vw,vh}}
function drawLayer(image,cam){const sx=(cam.x-WORLD.ox)/WORLD.w*image.width,sy=(cam.y-WORLD.oy)/WORLD.h*image.height,sw=cam.vw/WORLD.w*image.width,sh=cam.vh/WORLD.h*image.height;ctx.drawImage(image,sx,sy,sw,sh,0,0,W,H)}
function drawNPC(n,cam,z){const q=img[n.id],x=(n.x-cam.x)*z,y=(n.y-cam.y)*z,s=z*1.2;ctx.imageSmoothingEnabled=false;ctx.drawImage(q,x-q.width*s/2,y-q.height*s,q.width*s,q.height*s);ctx.imageSmoothingEnabled=true;label(n.name,x,y-q.height*s-5*z,'#f1dda6')}
function drawPlayer(cam,z){const rows={down:0,left:1,right:2,up:3},x=(player.x-cam.x)*z,y=(player.y-cam.y)*z,w=58*z,h=67*z;ctx.imageSmoothingEnabled=false;ctx.drawImage(img.player,frame*96,rows[player.f]*112,96,112,x-w/2,y-h,w,h);ctx.imageSmoothingEnabled=true;label('Aedric',x,y-h-6*z,'#fff4ce')}
function render(){const z=H>W?Math.max(1.08,Math.min(1.30,W/360*1.13)):Math.max(.84,Math.min(1.08,H/600)),cam=camera(z);ctx.setTransform(DPR,0,0,DPR,0,0);ctx.fillStyle='#071009';ctx.fillRect(0,0,W,H);ctx.imageSmoothingEnabled=true;drawLayer(img.bg,cam);const draw=[...NPC.map(n=>[n.y,'npc',n]),[player.y,'player',player]].sort((a,b)=>a[0]-b[0]);for(const d of draw)d[1]==='npc'?drawNPC(d[2],cam,z):drawPlayer(cam,z);drawLayer(img.fg,cam);const n=nearestNPC(78);if(n){$('prompt').textContent='Talk to '+n.name;$('prompt').classList.remove('hidden')}else $('prompt').classList.add('hidden')}
function update(dt){let d=null;for(const k of ['up','down','left','right'])if(held.has(k))d=k;if(d){player.f=d;const speed=118,dx=d==='left'?-speed*dt:d==='right'?speed*dt:0,dy=d==='up'?-speed*dt:d==='down'?speed*dt:0,nx=player.x+dx,ny=player.y+dy;if(valid(nx,ny)){player.x=nx;player.y=ny;walk+=Math.hypot(dx,dy);frame=(walk/11|0)%4;localStorage.setItem('breThiarMobileQA',JSON.stringify(player))}}else frame=0;if(toastUntil&&performance.now()>toastUntil){$('toast').classList.add('hidden');toastUntil=0}}
function loop(t){if(!running)return;const dt=Math.min(.05,(t-last)/1000||0);last=t;update(dt);render();requestAnimationFrame(loop)}
for(const b of document.querySelectorAll('[data-dir]')){const d=b.dataset.dir;b.addEventListener('pointerdown',e=>{e.preventDefault();held.add(d);player.f=d});for(const ev of ['pointerup','pointercancel','pointerleave'])b.addEventListener(ev,e=>{e.preventDefault();held.delete(d)})}
$('talk').addEventListener('pointerdown',e=>{e.preventDefault();const n=nearestNPC();if(!n)return toast('No one is close enough to talk to.');$('dialogName').textContent=n.name+' · '+n.role;$('dialogText').textContent=n.line;$('dialog').classList.remove('hidden')});$('dialogClose').onclick=()=>$('dialog').classList.add('hidden');$('menu').onclick=()=>$('panel').classList.remove('hidden');$('panelClose').onclick=()=>$('panel').classList.add('hidden');$('reset').onclick=()=>{player={x:WORLD.spawn[0],y:WORLD.spawn[1],f:'up'};localStorage.removeItem('breThiarMobileQA');$('panel').classList.add('hidden');toast('Position reset.')};
$('enter').addEventListener('click',()=>{try{const saved=JSON.parse(localStorage.getItem('breThiarMobileQA')||'null');if(saved&&valid(saved.x,saved.y))player={x:saved.x,y:saved.y,f:saved.f||'up'}}catch{}$('splash').classList.add('hidden');$('hud').classList.remove('hidden');running=true;last=performance.now();requestAnimationFrame(loop)});